table 'Key Measure'
	lineageTag: 8d79a48b-c0b0-4552-b123-1e447adb617a

	measure 'Cases Opened #' = ```
			
			COALESCE(CALCULATE(
			    DISTINCTCOUNT('case'[case_number]),
			    USERELATIONSHIP('case'[date_opened], 'Calendar'[Date])),0)
			
			```
		formatString: 0
		lineageTag: 24a79799-1d95-4661-84e8-a2b26502c26c

	measure 'Cases Closed #' =
			
			COALESCE(CALCULATE(
			    DISTINCTCOUNT('case'[case_number]),
			    USERELATIONSHIP('case'[date_closed], 'Calendar'[Date])),0)
		formatString: 0
		lineageTag: fa0b57cd-0f42-425c-88dc-759c067cf727

	measure 'Case #' = DISTINCTCOUNT('case'[case_number])
		formatString: 0
		lineageTag: a85efc74-f261-4a9f-959c-0300fe4583fc

	measure 'Planned (hr)' = ```
			
			COALESCE( 
			    CALCULATE(
			        SUM(on_demand_downtime_environment[downtime_minutes]) / 60.00,
			        
			        -- Filter conditions
			        on_demand_downtime[downtime_type] = "Planned",
			        NOT on_demand_downtime_environment[downtime_environment_status] IN { "Deferred", "Proposed" },
			        on_demand_downtime_environment[start_date] > EDATE(TODAY(), -12),
			        on_demand_downtime_environment[start_date] < TODAY(),
			        rapid_response_environment[rapid_response_environment_type] = "Production",
			        NOT CONTAINSSTRING(on_demand_downtime_environment[rr_enviornment], "DIS"),
			        NOT CONTAINSSTRING(on_demand_downtime_environment[rr_enviornment], "DTS")
			    ),
			    0
			)
			```
		lineageTag: 92672f7c-f0b1-4df0-8a3f-848e76aaab0c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unplanned (hr)' =
			
			COALESCE(CALCULATE (
			    SUM(on_demand_downtime_environment[downtime_minutes]) / 60.00,
			    on_demand_downtime[downtime_type] = "Unplanned",
			    NOT on_demand_downtime_environment[downtime_environment_status] IN { "Deferred", "Proposed" },
			    on_demand_downtime_environment[start_date] > EDATE(TODAY(), -12),
			    on_demand_downtime_environment[start_date] <= TODAY(),
			    rapid_response_environment[rapid_response_environment_type] = "Production",
			    NOT CONTAINSSTRING(on_demand_downtime_environment[rr_enviornment], "DIS"),
			    NOT CONTAINSSTRING(on_demand_downtime_environment[rr_enviornment], "DTS"),
			    on_demand_downtime[impacting_sla_uptime] = "Yes"
			), 0)
		formatString: 0.00
		lineageTag: 1632982e-62cb-4aec-bf02-b5c91aab6b81

	measure 'Unplanned Non SLA Impact (hr)' =
			
			COALESCE(CALCULATE (
			    SUM(on_demand_downtime_environment[downtime_minutes]) / 60.00,
			    on_demand_downtime[downtime_type] = "Unplanned",
			    NOT on_demand_downtime_environment[downtime_environment_status] IN { "Deferred", "Proposed" },
			    on_demand_downtime_environment[start_date] > EDATE(TODAY(), -12),  -- 4 quarters ago
			    on_demand_downtime_environment[start_date] <= TODAY(),
			    rapid_response_environment[rapid_response_environment_type] = "Production",
			    NOT CONTAINSSTRING(on_demand_downtime_environment[rr_enviornment], "DIS"),
			    NOT CONTAINSSTRING(on_demand_downtime_environment[rr_enviornment], "DTS"),
			    on_demand_downtime[impacting_sla_uptime] = "No"
			), 0)
		lineageTag: 6cbf89ff-94ad-46f9-865f-e283108b384b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Uptime %' =
			1 - DIVIDE(
			        COALESCE([Unplanned (hr)], 0.00),
			        COALESCE([Total Available Hour] - COALESCE([Planned (hr)], 0.00) + COALESCE([Unplanned Non SLA Impact (hr)], 0.00), 0.00),
			        0
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 34690cf8-8b2b-47e0-8c19-ee4c25506df2

	measure 'Total Available Hour' = ```
			
			CALCULATE(DATEDIFF (
			    MIN ( on_demand_downtime_environment[start_date] ),
			    EDATE ( MIN ( on_demand_downtime_environment[start_date] ), 3 ),
			    HOUR
			), 
			    NOT on_demand_downtime_environment[downtime_environment_status] IN { "Deferred", "Proposed" },
			    rapid_response_environment[rapid_response_environment_type] = "Production",
			    NOT CONTAINSSTRING(on_demand_downtime_environment[rr_enviornment], "DIS"),
			    NOT CONTAINSSTRING(on_demand_downtime_environment[rr_enviornment], "DTS")
			)
			
			```
		formatString: 0
		lineageTag: ce69c2fe-0462-4500-ae99-d97b4e308582

	measure 'Company Filter TN' = ```
			
			CALCULATE(
			    COUNTROWS(on_demand_downtime_environment),
			    TREATAS(
			        VALUES(account_active[account_id]),
			        rapid_response_environment[customer]
			    )
			)
			
			```
		formatString: 0
		lineageTag: 48f1e752-0d6e-417f-ba64-000343def823

	measure 'Memory Usage (GB)' = DIVIDE(SUM(memory_analysis[mem_usage_mb]), 1024)
		lineageTag: 594e6087-240b-469e-a0ae-5b8a6c9bb947

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Key Measure' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

