table Sheet1
	lineageTag: 649ed725-6a25-47ce-95e8-db01efcf54f5

	column Category
		dataType: string
		lineageTag: 097066ce-539b-4957-afe0-d80e5938120e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: be2fbf61-ee0b-405b-90c3-ce7fd4401b7c
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Weighting
		dataType: double
		lineageTag: e8f85363-2eae-4ec4-8e26-582f6ca672a1
		summarizeBy: sum
		sourceColumn: Weighting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\eberdichesky\Downloads\Categories and Weights.xlsx"), null, true),
				    #"Categories & Weighting_Sheet" = Source{[Item="Categories & Weighting",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Categories & Weighting_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Category", type text}, {"Subcategory", type text}, {"Weighting", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

