table Export
	lineageTag: a104db50-2d23-4b88-974c-de73cc6c7f1d

	column Quarter
		dataType: string
		lineageTag: c1da5603-ecfb-4dc4-8c70-34f2b4600217
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 5087e913-de69-4bce-8c01-795f6eadce71
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: a46bd3cd-52fb-4006-b9d8-1d2aa8b55c25
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column 2019-Q3
		dataType: string
		lineageTag: 1707787c-8a83-48de-9c44-b881390209c1
		summarizeBy: none
		sourceColumn: 2019-Q3

		annotation SummarizationSetBy = Automatic

	column 2021-Q4
		dataType: string
		lineageTag: e2484154-36c3-4291-b0bb-f3b0342e14a8
		summarizeBy: none
		sourceColumn: 2021-Q4

		annotation SummarizationSetBy = Automatic

	column 2022-Q1
		dataType: string
		lineageTag: b8c61d74-f1f6-4e5a-8028-386dbe34d664
		summarizeBy: none
		sourceColumn: 2022-Q1

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: string
		lineageTag: 758297fe-ae51-4c7c-9c03-ddbc18f4c18b
		summarizeBy: none
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

	partition Export = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\npanjabi.KINAXIS\Downloads\data (21).xlsx"), null, true),
				    Export_Sheet = Source{[Item="Export",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Quarter", type text}, {"Column2", type text}, {"Column3", type text}, {"2019-Q3", type any}, {"2021-Q4", type any}, {"2022-Q1", type any}, {"Total", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

